version: '2'

volumes:
  db-data:
    driver: local

services:
  db:
    image: mysql:5.7.18
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 6033:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: lunch_db
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 8088:3000
    links:
      - db:sql_srv
    depends_on:
      - db
    # Allows us to send signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
